apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS ride_db;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Pass@123"  # Align with docker-compose credentials
            - name: MYSQL_DATABASE
              value: "ma_project"
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: mysql-init
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  type: NodePort
  ports:
    - port: 3307
      targetPort: 3306
      nodePort: 30336
  selector:
    app: mysql-db