apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: rideshare/payment-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/microservices"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "microservices"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
  selector:
    app: payment-service